[package]
name = "lexington"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.3.0"
chumsky = { version = "1.0.0-alpha.4", features = ["label"] }
criterion = "0.5.1"
logos = "0.13.0"

[[bench]]
name = "benchy"
harness = false
